#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ovsdbapp
Version  : 0.12.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/83/fc/535f63c225d652f5b44fddf8e638d2d3a3818d5ae1f8b2791513bc0f9e7c/ovsdbapp-0.12.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/83/fc/535f63c225d652f5b44fddf8e638d2d3a3818d5ae1f8b2791513bc0f9e7c/ovsdbapp-0.12.1.tar.gz
Summary  : A library for creating OVSDB applications
Group    : Development/Tools
License  : Apache-2.0
Requires: ovsdbapp-python3
Requires: ovsdbapp-license
Requires: ovsdbapp-python
Requires: fixtures
Requires: netaddr
Requires: ovs
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : oslo.utils
BuildRequires : ovs
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pylint
BuildRequires : pytest
BuildRequires : stestr
BuildRequires : tox
BuildRequires : virtualenv

%description
ovsdbapp
        ===============================
        
        A library for creating OVSDB applications
        
        The ovdsbapp library is useful for creating applications that communicate

%package license
Summary: license components for the ovsdbapp package.
Group: Default

%description license
license components for the ovsdbapp package.


%package python
Summary: python components for the ovsdbapp package.
Group: Default
Requires: ovsdbapp-python3

%description python
python components for the ovsdbapp package.


%package python3
Summary: python3 components for the ovsdbapp package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ovsdbapp package.


%prep
%setup -q -n ovsdbapp-0.12.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536124477
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ovsdbapp
cp LICENSE %{buildroot}/usr/share/doc/ovsdbapp/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/ovsdbapp/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
