#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ovsdbapp
Version  : 0.13.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/8f/09/6f80c7937757574663eb878e47ebaef0c66dbe5ee1472b527230229d37eb/ovsdbapp-0.13.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/8f/09/6f80c7937757574663eb878e47ebaef0c66dbe5ee1472b527230229d37eb/ovsdbapp-0.13.0.tar.gz
Summary  : A library for creating OVSDB applications
Group    : Development/Tools
License  : Apache-2.0
Requires: ovsdbapp-python3
Requires: ovsdbapp-license
Requires: ovsdbapp-python
Requires: fixtures
Requires: netaddr
Requires: ovs
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : oslo.utils
BuildRequires : pbr

%description
ovsdbapp
        ===============================
        
        A library for creating OVSDB applications
        
        The ovdsbapp library is useful for creating applications that communicate

%package license
Summary: license components for the ovsdbapp package.
Group: Default

%description license
license components for the ovsdbapp package.


%package python
Summary: python components for the ovsdbapp package.
Group: Default
Requires: ovsdbapp-python3 = %{version}-%{release}

%description python
python components for the ovsdbapp package.


%package python3
Summary: python3 components for the ovsdbapp package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ovsdbapp package.


%prep
%setup -q -n ovsdbapp-0.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537973351
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ovsdbapp
cp LICENSE %{buildroot}/usr/share/doc/ovsdbapp/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/ovsdbapp/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
