#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ovsdbapp
Version  : 1.5.0
Release  : 22
URL      : https://files.pythonhosted.org/packages/bc/c5/84f486a45503af2a01d52b8640a9ff1344a5c9494cf1132f2d6c07726ab9/ovsdbapp-1.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/bc/c5/84f486a45503af2a01d52b8640a9ff1344a5c9494cf1132f2d6c07726ab9/ovsdbapp-1.5.0.tar.gz
Summary  : A library for creating OVSDB applications
Group    : Development/Tools
License  : Apache-2.0
Requires: ovsdbapp-license = %{version}-%{release}
Requires: ovsdbapp-python = %{version}-%{release}
Requires: ovsdbapp-python3 = %{version}-%{release}
Requires: fixtures
Requires: netaddr
Requires: ovs
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : fixtures
BuildRequires : netaddr
BuildRequires : oslo.utils
BuildRequires : ovs
BuildRequires : pbr

%description
ovsdbapp
        ========
        
        A library for creating OVSDB applications
        
        The ovdsbapp library is useful for creating applications that communicate

%package license
Summary: license components for the ovsdbapp package.
Group: Default

%description license
license components for the ovsdbapp package.


%package python
Summary: python components for the ovsdbapp package.
Group: Default
Requires: ovsdbapp-python3 = %{version}-%{release}

%description python
python components for the ovsdbapp package.


%package python3
Summary: python3 components for the ovsdbapp package.
Group: Default
Requires: python3-core
Provides: pypi(ovsdbapp)
Requires: pypi(fixtures)
Requires: pypi(netaddr)
Requires: pypi(ovs)
Requires: pypi(pbr)

%description python3
python3 components for the ovsdbapp package.


%prep
%setup -q -n ovsdbapp-1.5.0
cd %{_builddir}/ovsdbapp-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599602989
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ovsdbapp
cp %{_builddir}/ovsdbapp-1.5.0/LICENSE %{buildroot}/usr/share/package-licenses/ovsdbapp/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ovsdbapp/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
